#!/usr/bin/bash

# Copyright (c) 2015, David Bailey <robocoder.db@gmail.com>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
# OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

bacpac-usage() {
  echo 'bacpac version 0.1'
  echo 'Copyright (c) 2015 David Bailey <robocoder.db@gmail.com>'
  echo
  echo "usage: $0 update|restore"
  echo "   or: $0 help"
  echo
}

bacpac-setup() {
  cd "$(dirname "${BASH_SOURCE[0]}")"
  mkdir -p tmp
  pacman -Qqe > tmp/packages.list
  cp /etc/pacman.d/mirrorlist tmp/mirrorlist
  cp /etc/pacman.conf tmp/pacman.conf
}

if [[ "$#" != 1 ]]; then
  bacpac-usage
  exit 1
fi

if [[ "$1" == backup ]]; then
  bacpac-setup
  diff packages.list tmp/packages.list > tmp/packages.list.diff
  if [[ -s tmp/packages.list.diff ]]; then
    echo "Modifications to 'packages.list' since last backup:"
    cat tmp/packages.list.diff
    read -p "Back up? [Y/n] " response
    if [[ "$response" =~ ^[Yy]$ || "$response" == '' ]]; then
      mv tmp/packages.list packages.list
      git add packages.list
      git commit -m '' --allow-empty-message
      git push
    else
      echo false
    fi
  else
    echo "No modifications to 'packages.list' since last backup"
  fi
  rm tmp/packages.list.diff
elif [[ "$1" == restore ]]; then
  bacpac-setup
  echo 'Not implemented'
elif [[ "$1" == help ]]; then
  bacpac-usage
else
  bacpac-usage
  exit 1
fi
